# Generated by Django 3.0.8 on 2021-02-14 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210213_1832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
