# Generated by Django 4.1.4 on 2023-01-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=10)),
                ('updated_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
