# Generated by Django 4.1.4 on 2023-01-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_orders_download_delete_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_download',
            name='person_name',
            field=models.CharField(default='demo', max_length=20),
        ),
    ]
