# Generated by Django 4.1.4 on 2023-01-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_orders_download_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_download',
            name='place_order',
            field=models.BooleanField(default=False),
        ),
    ]
